@startuml

title __BUILDER's Class Diagram__\n

  namespace  {
    namespace om.groupjn.orderservice {
      namespace builder {
        class com.groupjn.orderservice.builder.Email {
            - message : String
            - recipients : String
            - title : String
            + Email()
            + Email()
            + equals()
            + getMessage()
            + getRecipients()
            + getTitle()
            + hashCode()
            + send()
            + setMessage()
            + setRecipients()
            + setTitle()
            + toString()
            # canEqual()
        }
      }
    }
  }
  

  namespace  {
    namespace om.groupjn.orderservice {
      namespace builder {
        class com.groupjn.orderservice.builder.EmailBuilder {
            - closing : String
            - greeting : String
            - mainText : String
            - recipients : Set<String>
            - title : String
            + addRecipient()
            + build()
            + removeRecipient()
            + setClosing()
            + setGreeting()
            + setMainText()
            + setTitle()
            - commaSeparatedRecipients()
        }
      }
    }
  }
  

  namespace  {
    namespace om.groupjn.orderservice {
      namespace builder {
        interface com.groupjn.orderservice.builder.IEmail {
            {abstract} + send()
        }
      }
    }
  }
  

  com.groupjn.orderservice.builder.Email .up.|> com.groupjn.orderservice.builder.IEmail


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
