eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

spring:
  application:
    name: service-registry
  zipkin:
    enabled: true
    base-url: ${ZIPKIN_SERVER:http://localhost:9411/}
  sleuth:
    enable: true

server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
