@startuml

title __MEMENTO's Class Diagram__\n

  namespace com.groupjn.cartservice {
    namespace memento {
      class com.groupjn.cartservice.memento.CartItem {
          - id : int
          - price : double
          - productId : int
          - qty : int
          - userId : int
          + CartItem()
          + CartItem()
          + CartItem()
          + CartItem()
          + Clone()
          + equals()
          + getId()
          + getPrice()
          + getProductId()
          + getQty()
          + getUserId()
          + hashCode()
          + setId()
          + setPrice()
          + setProductId()
          + setQty()
          + setUserId()
          + toString()
          # canEqual()
      }
    }
  }
  

  namespace com.groupjn.cartservice {
    namespace memento {
      class com.groupjn.cartservice.memento.CartItemsMementoTakeCarer {
          - _memento : List<CartItem>
          + CartItemsMementoTakeCarer()
          + Memento()
      }
    }
  }
  

  namespace com.groupjn.cartservice {
    namespace memento {
      interface com.groupjn.cartservice.memento.IMementoCareTaker {
          {abstract} + Memento()
      }
    }
  }
  

  namespace com.groupjn.cartservice {
    namespace memento {
      class com.groupjn.cartservice.memento.ShoppingCart {
          + id : int
          - _cartItems : List<CartItem>
          + AddItem()
          + RemoveItem()
          + Restore()
          + ShoppingCart()
          + equals()
          + getCartItem()
          + getId()
          + get_cartItems()
          + hashCode()
          + setId()
          + set_cartItems()
          + toString()
          # canEqual()
      }
    }
  }
  

  namespace com.groupjn.cartservice {
    namespace memento {
      class com.groupjn.cartservice.memento.ShoppingCartChangeTracker {
          - _stack : Stack<IMementoCareTaker<List<CartItem>>>
          + Save()
          + ShoppingCartChangeTracker()
          + Undo()
      }
    }
  }
  

  com.groupjn.cartservice.memento.CartItemsMementoTakeCarer .up.|> com.groupjn.cartservice.memento.IMementoCareTaker
  com.groupjn.cartservice.memento.ShoppingCartChangeTracker o-- com.groupjn.cartservice.memento.ShoppingCart : _shoppingCart


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
