server:
  port: ${port:9190}
spring:
  application:
    name: APIGATEWAY-SERVICE
  zipkin:
    enabled: true
    base-url: ${ZIPKIN_SERVER:http://localhost:9411/}
  sleuth:
    enable: true
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://order-service:9192/
          predicates:
            - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: order-service
                fallbackuri: forward:/orderFallBack
        - id: payment-service
          uri: http://payment-service:9193/
          predicates:
            - Path=/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: payment-service
                fallbackuri: forward:/paymentFallBack
        - id: cart-service
          uri: http://cart-service:9194/
          predicates:
            - Path=/cart/**
          filters:
            - name: CircuitBreaker
              args:
                name: cart-service
                fallbackuri: forward:/cartFallBack
        - id: authentication-service
          uri: http://authentication-service:9191/
          predicates:
            - Path=/oauth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authentication-service
                fallbackuri: forward:/authenticationFallBack
        - id: product-service
          uri: http://product-service:9190/
          predicates:
            - Path=/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: product-service
                fallbackuri: forward:/productFallBack
        - id: user-service
          uri: http://user-service:8105/
          predicates:
            - Path=/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackuri: forward:/userFallBack
        - id: api-gateway
          uri: http://api-gateway:9190/
          predicates:
            - Path=/analysis/**
          filters:
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackuri: forward:/apiFallBack

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000



