server:
  port: 9191
spring:
  h2:
    console:
      enabled: true
  application:
    name: PAYMENT-SERVICE

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8989/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin