server:
  port: 9191
spring:
  application:
    name: AUTHENTICATION-SERVICE
  zipkin:
    enabled: true
    base-url: ${ZIPKIN_SERVER:http://localhost:9411/}
  sleuth:
    enable: true
  datasource:
    url: jdbc:h2:mem:userdb?createDatabaseIfNotExist=true
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
logging:
  file:
    path: ~/Documents/Microservices/GroupProject/logs/microservice.log

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka
  instance:
    leaseRenewalIntervalInSeconds: 5
    preferIpAddress: true