server:
  port: ${port:9196}

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:h2:mem:userdb?createDatabaseIfNotExist=true
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect



inputDirectory: ""