server:
  port: 8005

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:8889/userdb?createDatabaseIfNotExist=true
    username: root
    password: passme@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8989/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin

