server:
  port: ${port:9195}
spring:
  h2:
    console:
      enabled: true
  application:
    name: PRODUCT-SERVICE
  zipkin:
    enabled: true
    base-url: ${ZIPKIN_SERVER:http://localhost:9411/}
  sleuth:
    enable: true
security:
  oauth2:
    resource:
      token-info-uri: http://authentication-service:9191/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

axon:
  axonserver:
    servers: "lo:8124"





